# Generated by Django 4.2.7 on 2023-12-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=128)),
                ('Auteur', models.CharField(max_length=128)),
                ('Date_de_production', models.CharField(max_length=128)),
                ('Adresse', models.CharField(max_length=128)),
                ('Mot_cle', models.CharField(max_length=128)),
                ('Format', models.CharField(max_length=128)),
                ('NB_PAGES', models.IntegerField(default=1)),
                ('Categorie', models.CharField(max_length=128)),
                ('Note_resume', models.TextField(blank=True)),
                ('Couverture', models.ImageField(upload_to='boky')),
                ('Fichier', models.FileField(upload_to='boky')),
            ],
        ),
    ]
