# Generated by Django 4.2.7 on 2023-12-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='slug',
            field=models.SlugField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
