# Generated by Django 4.2.7 on 2024-01-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Livre', '0006_remove_livre_slug_alter_livre_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livre',
            options={'verbose_name_plural': 'Documents'},
        ),
    ]
