# Generated by Django 4.2.7 on 2024-01-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Livre', '0007_alter_livre_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livre',
            new_name='Document',
        ),
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
    ]
